(() => {
  "use strict";
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const fmt=new Intl.NumberFormat("zh-CN",{maximumFractionDigits:1});
  const state={catalog:[],profiles:[],transparency:[],availability:[],history:[],submissionLog:[],evidence:[],profileMap:new Map(),transparencyMap:new Map(),availabilityMap:new Map(),evidenceMap:new Map(),filter:"ALL",selectedPark:null,evidenceLimit:40};
  const c55Priority={UNKNOWN:0,PLANNED:1,PILOT:2,SELECTED_FOR_CONSTRUCTION:3,DESIGNATED:4};
  const verifiedEvidenceLevels=new Set(["E3_OFFICIAL_SECONDARY","E4_OFFICIAL_PRIMARY"]);
  const statusLabels={PUBLIC_AVAILABLE:"公开可得",CALCULABLE:"可计算",PARK_SURVEY_REQUIRED:"园区填报",ENTERPRISE_REQUIRED:"企业填报",MONITORING_REQUIRED:"监测系统",DEFINITION_PENDING:"定义待决","N/A":"不适用",MISSING:"缺失"};
  const dimensions={A:"A 产业发展",B:"B 创新驱动",C:"C 可持续发展",D:"D 数智赋能"};
  const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const num=v=>Number.isFinite(Number(v))?Number(v):0;
  function toast(text){const el=$("#toast");el.textContent=text;el.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),2200)}
  function parseCsv(text){const rows=[];let row=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++}else if(c==='"')quoted=!quoted;else if(c===','&&!quoted){row.push(cell);cell=""}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&n==='\n')i++;row.push(cell);cell="";if(row.some(v=>v.trim()))rows.push(row);row=[]}else cell+=c}row.push(cell);if(row.some(v=>v.trim()))rows.push(row);const headers=(rows.shift()||[]).map(x=>x.replace(/^\ufeff/,""));return rows.map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]||""])))}
  async function csv(name){const res=await fetch(`data/${name}`,{cache:"no-store"});if(!res.ok)throw new Error(`${name}: ${res.status}`);return parseCsv(await res.text())}
  function currentHistoryRow(rows){return rows.filter(r=>r.Reviewed_Status==="ACCEPTED"&&verifiedEvidenceLevels.has(r.Evidence_Level)).sort((a,b)=>(c55Priority[b.Recognition_Status]??-1)-(c55Priority[a.Recognition_Status]??-1)||num(b.Year)-num(a.Year))[0]||null}
  function deriveProfilesFromHistory(){state.profiles.forEach(profile=>{const rows=state.history.filter(r=>r.Park_ID===profile.Park_ID),current=currentHistoryRow(rows);if(current){profile.C55P_Status=current.Recognition_Status;profile.C55P_Level=current.Recognition_Level;profile.C55P_Year=current.Year;profile.C55P_Source_Title=current.Source_Title;profile.C55P_Publisher=current.Publisher;profile.C55P_URL=current.URL;profile.C55P_Evidence_ID=current.Evidence_ID}profile.C55P_History_Count=String(rows.length);profile._Last_Verified_Date=rows.map(r=>r.Last_Verified_Date).filter(Boolean).sort().at(-1)||"—";profile._Evidence_Count=String(new Set(rows.map(r=>r.Evidence_ID).filter(Boolean)).size)})}
  async function load(){const [catalog,profiles,transparency,availability,history,submissionLog,evidence]=await Promise.all([csv("park_catalog.csv"),csv("park_profiles.csv"),csv("park_transparency.csv"),csv("park_indicator_availability.csv"),csv("c55p_status_history.csv"),csv("c55p_submission_log.csv"),csv("park_public_evidence.csv")]);state.catalog=catalog.filter(r=>r.region_scope==="国内园区");state.profiles=profiles;state.transparency=transparency;state.availability=availability;state.history=history;state.submissionLog=submissionLog;state.evidence=evidence;deriveProfilesFromHistory();profiles.forEach(r=>state.profileMap.set(r.Park_ID,r));transparency.forEach(r=>state.transparencyMap.set(r.Park_ID,r));availability.forEach(r=>{if(!state.availabilityMap.has(r.Park_ID))state.availabilityMap.set(r.Park_ID,[]);state.availabilityMap.get(r.Park_ID).push(r)});evidence.forEach(r=>state.evidenceMap.set(r.evidence_id,r));if(state.catalog.length!==67||state.profiles.length!==67)throw new Error("67园区数据未完整加载");state.selectedPark=state.catalog[0].park_id}
  function c55Label(status){return status==="DESIGNATED"?"正式认定":status==="SELECTED_FOR_CONSTRUCTION"?"建设名单":status==="PILOT"?"试点":status==="PLANNED"?"规划建设":"状态待核实"}
  function badge(status){return `<span class="badge ${status==="DESIGNATED"?"designated":"selected"}">${c55Label(status)}</span>`}
  function initHero(){const counts=state.profiles.reduce((o,r)=>(o[r.C55P_Status]=(o[r.C55P_Status]||0)+1,o),{});const cards=[[state.profiles.length,"园区"],[counts.DESIGNATED||0,"正式认定"],[counts.SELECTED_FOR_CONSTRUCTION||0,"建设名单"],[new Set(state.availability.map(r=>r.Indicator_ID)).size,"评价指标"]];$("#heroStats").innerHTML=cards.map(([v,l])=>`<div class="hero-stat"><strong>${fmt.format(v)}</strong><span>${l}</span></div>`).join("");$("#dataStamp").textContent=`数据规模：${state.profiles.length}园区 × ${new Set(state.availability.map(r=>r.Indicator_ID)).size}指标`}
  function coords(p){return{x:Math.max(1,Math.min(99,(num(p.longitude)-65)/(150-65)*100)),y:Math.max(1,Math.min(99,(56-num(p.latitude))/(56-15)*100))}}
  function filteredParks(){const q=$("#parkSearch").value.trim().toLowerCase();return state.catalog.filter(p=>{const profile=state.profileMap.get(p.park_id);let ok=state.filter==="ALL"||state.filter==="NATIONAL"&&p.level==="国家级"||state.filter==="GUANGDONG"&&p.level!=="国家级"||profile?.C55P_Status===state.filter;const text=[p.park_name,p.province,p.city,p.industry_group].join(" ").toLowerCase();return ok&&(!q||text.includes(q))})}
  function renderMap(){const parks=filteredParks();$("#mapCount").textContent=`${parks.length} 个园区`;$("#markers").innerHTML=parks.map(p=>{const pos=coords(p),status=state.profileMap.get(p.park_id)?.C55P_Status;return `<button class="marker ${status==="DESIGNATED"?"designated":"selected"} ${state.selectedPark===p.park_id?"active":""}" style="left:${pos.x}%;top:${pos.y}%" data-id="${esc(p.park_id)}" title="${esc(p.park_name)}" aria-label="查看${esc(p.park_name)}"></button>`}).join("");$$(".marker").forEach(b=>b.addEventListener("click",()=>selectPark(b.dataset.id,true)))}
  function publicEvidence(parkId){return state.evidence.filter(r=>r.park_id===parkId)}
  function renderMapDetail(id){const p=state.catalog.find(x=>x.park_id===id),profile=state.profileMap.get(id),t=state.transparencyMap.get(id);if(!p||!profile)return;$("#mapDetail").innerHTML=`${badge(profile.C55P_Status)}<h3 class="park-title">${esc(p.park_name)}</h3><div class="sub">${esc([p.province,p.city,p.level].filter(Boolean).join(" · "))}</div><div class="fact-grid"><div class="fact"><span>园区类型</span><strong>${esc(p.boundary_type||"待核实")}</strong></div><div class="fact"><span>主导产业</span><strong>${esc(p.industry_group||"待确认")}</strong></div><div class="fact"><span>C55-P年份</span><strong>${esc(profile.C55P_Year||"—")}</strong></div><div class="fact"><span>Evidence ID</span><strong>${esc(profile.C55P_Evidence_ID||"—")}</strong></div></div><h4>公开数据情况</h4><div class="fact-grid"><div class="fact"><span>Direct Public Data</span><strong>${esc(t.Direct_Public_Data_Count)}</strong></div><div class="fact"><span>Calculated Public Data</span><strong>${esc(t.Calculated_Public_Data_Count)}</strong></div><div class="fact"><span>Official Evidence</span><strong>${esc(t.Official_Evidence_Count)}</strong></div><div class="fact"><span>Missing</span><strong>${esc(t.Missing_Count)}</strong></div></div><a class="source-link" href="${esc(profile.C55P_URL)}" target="_blank" rel="noopener">${esc(profile.C55P_Source_Title)} · ${esc(profile.C55P_Publisher)} ↗</a><br><button class="button" id="openProfile">查看完整画像</button>`;$("#openProfile").addEventListener("click",()=>{$("#profileSelect").value=id;renderProfile(id);$("#profiles").scrollIntoView({behavior:"smooth"})})}
  function selectPark(id,detail=false){state.selectedPark=id;renderMap();renderMapDetail(id);if(detail&&innerWidth<980)$("#mapDetail").scrollIntoView({behavior:"smooth",block:"center"})}
  function initMap(){$$(".filter").forEach(b=>b.addEventListener("click",()=>{state.filter=b.dataset.filter;$$('.filter').forEach(x=>x.classList.toggle('active',x===b));renderMap()}));$("#parkSearch").addEventListener("input",renderMap);renderMap()}
  function mainGaps(rows){return rows.filter(r=>!["PUBLIC_AVAILABLE","CALCULABLE","N/A"].includes(r.Availability_Status)).slice(0,10)}
  function renderProfile(id){
    state.selectedPark=id;
    const p=state.catalog.find(x=>x.park_id===id),profile=state.profileMap.get(id),t=state.transparencyMap.get(id),rows=state.availabilityMap.get(id)||[],gaps=mainGaps(rows),evidence=publicEvidence(id);
    $("#profileContent").innerHTML=`<article class="profile-card"><h3>基本信息</h3><h2 class="park-title">${esc(p.park_name)}</h2><div class="sub">${esc(p.province)} · ${esc(p.city)} · ${esc(p.level)}</div><div class="fact-grid"><div class="fact"><span>园区类型</span><strong>${esc(p.boundary_type||"待核实")}</strong></div><div class="fact"><span>主导产业</span><strong>${esc(p.industry_group||"待确认")}</strong></div><div class="fact"><span>建设周期</span><strong>${esc(p.construction_period||"—")}</strong></div><div class="fact"><span>Park ID</span><strong>${esc(id)}</strong></div></div></article><article class="profile-card c55-profile"><h3>绿色低碳建设状态</h3>${badge(profile.C55P_Status)}<div class="fact-grid"><div class="fact"><span>C55-P</span><strong>${esc(profile.C55P_Status)}</strong></div><div class="fact"><span>年份</span><strong>${esc(profile.C55P_Year)}</strong></div><div class="fact"><span>历史状态</span><strong>${esc(profile.C55P_History_Count)}条</strong></div><div class="fact"><span>证据数量</span><strong>${esc(profile._Evidence_Count)}</strong></div><div class="fact"><span>最后核验</span><strong>${esc(profile._Last_Verified_Date)}</strong></div><div class="fact"><span>当前证据</span><strong>${esc(profile.C55P_Evidence_ID)}</strong></div></div><a class="source-link" href="${esc(profile.C55P_URL)}" target="_blank" rel="noopener">查看状态来源 ↗</a><div class="profile-actions"><button class="button" data-history-park="${esc(id)}">查看历史</button><button class="button primary" data-open-contribution="UPDATE" data-contribute-park="${esc(id)}">补充 / 更新该园区状态</button></div></article><article class="profile-card"><h3>公开数据情况</h3><div class="data-bars">${[["Direct Public Data",t.Direct_Public_Data_Count,t.Applicable_Indicators],["Calculated Public Data",t.Calculated_Public_Data_Count,t.Applicable_Indicators],["Official Evidence",t.Official_Evidence_Count,t.Applicable_Indicators],["Missing",t.Missing_Count,t.Applicable_Indicators]].map(([l,v,d])=>`<div class="data-bar"><span>${l}</span><i class="track"><i style="width:${Math.min(100,num(v)/Math.max(1,num(d))*100)}%"></i></i><strong>${esc(v)}</strong></div>`).join("")}</div><p class="sub">这些计数说明公开信息完整程度，不是绩效结果。</p></article><article class="profile-card"><h3>主要数据缺口</h3><div class="gap-list">${gaps.map(r=>`<div class="gap-item"><strong>${esc(r.Indicator_ID)} ${esc(r.Indicator_Name)}</strong><br><span>${esc(statusLabels[r.Availability_Status])} · ${esc(r.Responsible_Department)}</span></div>`).join("")}</div></article><article class="profile-card wide"><h3>查看证据</h3><div class="evidence-list">${evidence.length?evidence.slice(0,12).map(e=>`<div class="evidence-item"><p><strong>${esc(e.evidence_id)}</strong> · ${esc(e.statement)}</p><span class="sub">${esc(e.publisher||e.source_title)} · ${esc(e.year||e.date)}</span>${e.source_url?`<br><a class="source-link" href="${esc(e.source_url)}" target="_blank" rel="noopener">原始来源 ↗</a>`:""}</div>`).join(""):'<div class="empty">暂无可关联证据</div>'}</div></article>`;
    $("#matrixSelect").value=id;renderMatrix(id)
  }
  function initProfiles(){const opts=state.catalog.map(p=>`<option value="${esc(p.park_id)}">${esc(p.park_name)}</option>`).join("");$("#profileSelect").innerHTML=opts;$("#matrixSelect").innerHTML=opts;$("#profileSelect").addEventListener("change",e=>renderProfile(e.target.value));$("#matrixSelect").addEventListener("change",e=>renderMatrix(e.target.value));renderProfile(state.selectedPark)}
  function renderTransparency(){const key=$("#transparencySort").value,desc=key!=="Missing_Rate",rows=[...state.transparency].sort((a,b)=>(desc?-1:1)*(num(a[key])-num(b[key])));const avg=k=>rows.reduce((s,r)=>s+num(r[k]),0)/rows.length;$("#transparencySummary").innerHTML=[["平均直接公开率",avg("Direct_Public_Data_Rate")],["平均官方证据率",avg("Official_Evidence_Rate")],["平均近期数据率",avg("Recent_Data_Rate")],["平均缺失率",avg("Missing_Rate")]].map(([l,v])=>`<div class="summary-card"><strong>${fmt.format(v*100)}%</strong><span>${l}</span></div>`).join("");$("#transparencyBars").innerHTML=rows.map(r=>`<div class="transparency-row"><strong>${esc(r.Park_Name)}</strong>${[["直接",r.Direct_Public_Data_Rate],["官方",r.Official_Evidence_Rate],["近期",r.Recent_Data_Rate],["缺失",r.Missing_Rate]].map(([l,v])=>`<div class="tiny-bar"><span>${l}<b>${fmt.format(num(v)*100)}%</b></span><i><b style="width:${num(v)*100}%"></b></i></div>`).join("")}</div>`).join("")}
  function initTransparency(){$("#transparencySort").addEventListener("change",renderTransparency);renderTransparency()}
  function renderMatrix(id){const rows=state.availabilityMap.get(id)||[],counts=rows.reduce((o,r)=>(o[r.Availability_Status]=(o[r.Availability_Status]||0)+1,o),{});$("#readinessSummary").innerHTML=Object.entries(counts).map(([s,v])=>`<div class="summary-card"><strong>${v}</strong><span>${esc(statusLabels[s]||s)}</span></div>`).join("");$("#matrixLegend").innerHTML=Object.entries(statusLabels).map(([s,l])=>`<span class="status-chip ${s.toLowerCase().replace(/[^a-z]/g,'-')}">${l}</span>`).join("");$("#indicatorMatrix").innerHTML=Object.entries(dimensions).map(([d,title])=>`<section class="dimension"><h3>${title}</h3>${rows.filter(r=>r.Dimension===d).map(r=>{const ev=state.evidenceMap.get(r.Evidence_ID);return `<details class="indicator" data-indicator-id="${esc(r.Indicator_ID)}"><summary><strong>${esc(r.Indicator_ID)}</strong><span>${esc(r.Indicator_Name)}</span><em>${esc(statusLabels[r.Availability_Status]||r.Availability_Status)}</em></summary><div class="indicator-detail"><dl><dt>指标定义</dt><dd>${esc(r.Definition||"—")}</dd><dt>单位</dt><dd>${esc(r.Unit||"—")}</dd><dt>数据来源需求</dt><dd>${esc(r.Evidence_Requirement||"—")}</dd><dt>当前状态</dt><dd>${esc(r.Availability_Status)}</dd><dt>证据</dt><dd>${esc(r.Evidence_ID||"暂无")}${ev?.source_url?` · <a class="source-link" href="${esc(ev.source_url)}" target="_blank" rel="noopener">来源 ↗</a>`:""}</dd><dt>缺失原因</dt><dd>${esc(r.Missing_Reason||"—")}</dd><dt>责任部门</dt><dd>${esc(r.Responsible_Department||"—")}</dd><dt>需要补充的数据</dt><dd>${esc(r.Required_Data||"—")}</dd></dl></div></details>`}).join("")}</section>`).join("")}
  function initC55(){const groups={DESIGNATED:[],SELECTED_FOR_CONSTRUCTION:[]};state.profiles.forEach(r=>groups[r.C55P_Status]?.push(r));$("#c55Stats").innerHTML=[["正式认定",groups.DESIGNATED.length],["建设名单",groups.SELECTED_FOR_CONSTRUCTION.length]].map(([l,v])=>`<div class="c55-stat"><strong>${v}</strong><span>${l}</span></div>`).join("");const render=(id,rows)=>{$(id).innerHTML=rows.map(r=>`<button data-id="${esc(r.Park_ID)}">${esc(r.Park_Name)} · ${esc(r.C55P_Year)}</button>`).join("");$$(`${id} button`).forEach(b=>b.addEventListener("click",()=>{$("#profileSelect").value=b.dataset.id;renderProfile(b.dataset.id);$("#profiles").scrollIntoView({behavior:"smooth"})}))};render("#designatedList",groups.DESIGNATED);render("#selectedList",groups.SELECTED_FOR_CONSTRUCTION);$("#historyList").innerHTML=state.history.slice().sort((a,b)=>num(b.Year)-num(a.Year)).map(r=>`<div class="history-item"><strong>${esc(r.Park_Name)}</strong><br>${esc(c55Label(r.Recognition_Status))} · ${esc(r.Year)} · ${esc(r.Evidence_ID)}${r.URL?`<br><a class="source-link" href="${esc(r.URL)}" target="_blank" rel="noopener">来源 ↗</a>`:""}</div>`).join("")}
  function renderEvidence(){const q=$("#evidenceSearch").value.trim().toLowerCase(),parks=new Map(state.catalog.map(p=>[p.park_id,p.park_name]));const rows=state.evidence.filter(e=>[e.evidence_id,parks.get(e.park_id),e.statement,e.publisher,e.metric].join(" ").toLowerCase().includes(q));$("#evidenceTable").innerHTML=rows.slice(0,state.evidenceLimit).map(e=>`<tr><td>${esc(e.evidence_id)}</td><td>${esc(parks.get(e.park_id)||e.park_id)}</td><td>${esc(e.statement)}</td><td>${esc(e.publisher||e.source_title)}<br>${esc(e.year||e.date)}</td><td>${e.source_url?`<a class="source-link" href="${esc(e.source_url)}" target="_blank" rel="noopener">查看来源 ↗</a>`:"仅本地正式文件"}</td></tr>`).join("");$("#moreEvidence").hidden=state.evidenceLimit>=rows.length}
  function initEvidence(){$("#evidenceSearch").addEventListener("input",()=>{state.evidenceLimit=40;renderEvidence()});$("#moreEvidence").addEventListener("click",()=>{state.evidenceLimit+=40;renderEvidence()});renderEvidence()}
  async function init(){try{await load();initHero();initMap();initProfiles();initTransparency();renderMatrix(state.selectedPark);initC55();initEvidence();document.dispatchEvent(new CustomEvent("atlas:data-ready",{detail:{catalog:state.catalog.map(r=>({...r})),history:state.history.map(r=>({...r})),submissionLog:state.submissionLog.map(r=>({...r})),profiles:state.profiles.map(r=>({...r}))}}))}catch(error){document.body.innerHTML=`<main class="section"><div class="empty"><strong>数据加载失败</strong><span>${esc(error.message)}</span></div></main>`;console.error(error)}}
  init();
})();
